config/routes.rb
Rails.application.routes.draw do
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #mount ActionCable.server => '/cable'
  root  'main#home'
  
  
  get   '/signup',   to:'users#new'
  post  '/signup',   to:'users#create'
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'sessions/new'

  resources :threadtitles
  get 'threadtitlehome',    to:'threadtitles#index'
  post 'threadtitlehome',    to:'threadtitles#create'
  get 'threadtitles/:threadtitle_id' => 'threadtitles#show'
  get '/list',  to:'threadtitles#all'
  
  resources :users

  resources :messages

end

app/models/threadtitle.rb
class Threadtitle < ApplicationRecord
   has_many :messages, dependent: :destroy#dependentはルームが消えたら紐づけられたpostも消されるようにするため
   
end

app/controllers/threadtitles_controller.rb
class ThreadtitlesController < ApplicationController

  # GET /threadtitles
  # GET /threadtitles.json
  def index
    @threadtitles = Threadtitle.all
  end

  def all
    @threadtitles = Threadtitle.all
  end
  # GET /threadtitles/1
  # GET /threadtitles/1.json
  def show
    if logged_in?
      @threadtitle = Threadtitle.find(params[:id])
      @messages = @threadtitle.messages
    end
  end

  # GET /threadtitles/new
  def new
    @threadtitle = Threadtitle.new(threadtitle_params)
  end

  # GET /threadtitles/1/edit
  def edit
  end

  # POST /threadtitles
  # POST /threadtitles.json
  def create
    @threadtitle = Threadtitle.new(threadtitle_params)
    if @threadtitle.save
      redirect_to @threadtitle
    else
      flash[:danger] = 'Invalid'
      redirect_to threadtitlehome_path
    end
  end

  # PATCH/PUT /threadtitles/1
  # PATCH/PUT /threadtitles/1.json
  def update
    respond_to do |format|
    end
  end

  # DELETE /threadtitles/1
  # DELETE /threadtitles/1.json
  def destroy
    @threadtitle.destroy
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def threadtitle_params
      params.require(:threadtitle).permit(:name)
    end
end

app/helpers/threadtitles_helper.rb
module ThreadtitlesHelper
end

app/views/threadtitles/all.html.erb
<%= render 'layouts/header'%>
<ul class = "threadtitles_list">
  <% @threadtitles.each do |threadtitle| %>
    <li>
      <div class="link">
        <%= link_to "#{threadtitle.name}", "/threadtitles/#{threadtitle.id}/" %>
      </div>
      <div class="info">
        <p><%= threadtitle.created_at %></p>
      </div>
    </li>
  <% end %>
</ul>

<br>

app/views/threadtitles/edit.html.erb
<%= render 'layouts/header'%>
<h1>Editing Threadtitle</h1>

<!--<%= render 'form', threadtitle: @threadtitle %>-->

<%= link_to 'Show', @threadtitle %> |
<%= link_to 'Back', threadtitles_path %>
echo "# app" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/kei004/app.git
git push -u origin master

app/views/threadtitles/index.html.erb
<%= render 'layouts/header'%>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div class = "Threadtitle-body">
  <div class = "threadtitle-form">
    <%= form_for(:threadtitle, url: threadtitlehome_path) do |f| %>

      <%= f.label :タイトル %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'タイトル'%>

      <%= f.submit "Create", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/threadtitles/new.html.erb
<%= render 'layouts/header'%>
<h1>New Threadtitle</h1>

<%= render 'form', threadtitle: @threadtitle %>

<%= link_to 'Back', threadtitles_path %>

app/views/threadtitles/show.html.erb
<%= render 'layouts/header'%>
<div class = "chatthreadtitle">
    <div class = "chat-body" >
         <div id = "chat-list">
            <h1><%=@threadtitle.name%></h1>
        </div>
        <div id = "chat-details">
            <div id = "see">
                <p id= "live"> Live</p><p id = "number">2,289</p>
            </div>
        </div>
        <div class = "chat-main">
            <div id = "chat-contents">
                <div id="messages", data-threadtitle_id="<%= @threadtitle.id %>">
                    <div class = "messages-main">
                        <%= render @messages %>
                    </div>
                </div>
            </div>
            <div id = "chat-form">
                <form>
                <input class="textbutton" type="text" data-behavior="threadtitle_speaker">
                </form>
            </div>
        </div>
    </div>
</div>